export default function Head() {
  return (
    <head>
      <title>loophole</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {/* eslint-disable-next-line @next/next/no-page-custom-font*/}
      <link
        href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500;700&display=swap"
        rel="stylesheet"></link>
    </head>
  );
}
